apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    env:
    - name: MESSAGE
      value: "MSRIT"
    command: ["/bin/echo"]
    args: ["$(MESSAGE)"]